# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 152efead92cf91621c0167d5d0207a477eeadea2546697424b289fcc8d054706be8adc7e3c64ccfe05d1eb21dc7d9e916f80a2c076f2eab6c340b4ec916911e4

test:
  secret_key_base: 870d05ad95d151a2dc2e6efd0a89b4f6bf8ddf75c682271a669adb0303ff9ad0ca9548c4f925b4d9c59ee97b42f00dbffc565f951d2e00d752a65ebd8a3083e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
